import re
from abc import ABC
from typing import Optional
from agent_layer.agent_actor import AgentActor, ReasoningCallback
from agent_layer.llm_agents.LLMs.llm_selector import get_llm

class LLMAgent(AgentActor, ABC):
    """
    Abstract Base Class for Large Language Model (LLM) based agents.
    
    This intermediate layer acts as a bridge between the generic AgentActor 
    and specific LLM implementations. Its responsibilities are:
    1. initializing the appropriate LLM client based on a model identifier.
    2. Providing utilities to parse structured commands (actions) from unstructured chat responses.
    """

    def __init__(self, model_name: str, on_reasoning: Optional[ReasoningCallback] = None):
        """
        Initialize the LLM Agent.

        Args:
            model_name (str): The identifier of the model to be loaded via the factory (e.g., 'gpt-4').
            on_reasoning (ReasoningCallback, optional): A callback function to handle real-time 
                                                        streaming of the agent's internal reasoning.
        """
        super().__init__(on_reasoning)
        self.model_name = model_name
        
        self.llm_client = get_llm(model_name)

    def _extract_action(self, response_text: str) -> str:
        """
        Parses the action command from the raw text response generated by the LLM.
        
        It searches for a specific pattern (e.g., 'action: { command }') to separate 
        the executable command from the reasoning text.

        Args:
            response_text (str): The complete string output from the LLM.

        Returns:
            str: The content found inside the action brackets.
                 Returns the original text if no pattern is matched (fallback).
        """
        # Supported formats: "action: { jump }", "ACTION:{attack}", "Action: { open door }"
        pattern = r'action\s*:\s*\{(.*?)\}'
        match = re.search(pattern, response_text, flags=re.IGNORECASE | re.DOTALL)

        if not match:
            # Fallback: Return the raw text. 
            # This allows the Game Engine to decide if the raw output is a valid command 
            # or if it should return an "Unknown command" error to the agent.
            return response_text.strip()

        return match.group(1).strip()
    

    